### ISSUE TITLE
the trained model can't download

### ISSUE THREAD

**Issue by hellozjr** [DolotovEvgeniy/face-detection-model#3]
when i download the model,got message "The folder that you were viewing no longer exists or you no longer have permission to access it."

**Comment by DolotovEvgeniy** [comment]
I have opened access. Try the download again.

**Comment by hellozjr** [comment]
thank you very much,but i try many times,and can't download it complete,can you email to me? thanks.

------------------ 原始邮件 ------------------
发件人: "DolotovEvgeniy";notifications@github.com;
发送时间: 2016年3月18日(星期五) 晚上6:13
收件人: "DolotovEvgeniy/face-detection-model"face-detection-model@noreply.github.com; 
抄送: "zjr"502741025@qq.com; 
主题: Re: [face-detection-model] the trained model can't download (#3)

I have open access. Try the download again.

**Comment by DolotovEvgeniy** [comment]
@hellozjr , Write to me at dolotov.evgeniy@gmail.com and I will send you the trained model.

**Comment by hellozjr** [comment]
thanks,i download it yesterday night.

------------------ 原始邮件 ------------------
发件人: "DolotovEvgeniy";notifications@github.com;
发送时间: 2016年3月22日(星期二) 凌晨1:59
收件人: "DolotovEvgeniy/face-detection-model"face-detection-model@noreply.github.com; 
抄送: "zjr"502741025@qq.com; 
主题: Re: [face-detection-model] the trained model can't download (#3)

@hellozjr , Write to me at dolotov.evgeniy@gmail.com and I will send you the trained model.
